### ISSUE TITLE
if (!options.httpModule) throw new Error("Invalid protocol"); 

### ISSUE THREAD

**Issue by abr4xas** [mikeal/planet#5]
Hi there!! 

``` node
node test.js 

/home/abr4xas/Proyectos/planet/node_modules/request/main.js:201
  if (!options.httpModule) throw new Error("Invalid protocol");
                                 ^
Error: Invalid protocol
    at Request.request (/home/abr4xas/Proyectos/planet/node_modules/request/main.js:201:34)
    at request (/home/abr4xas/Proyectos/planet/node_modules/request/main.js:359:5)
    at Function.request.defaults.d (/home/abr4xas/Proyectos/planet/node_modules/request/main.js:371:14)
    at Object.exports.get (/home/abr4xas/Proyectos/planet/feedstream.js:204:19)
    at test (/home/abr4xas/Proyectos/planet/test.js:15:27)
    at Object.<anonymous> (/home/abr4xas/Proyectos/planet/test.js:11:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

```

**Comment by danmactough** [comment]
@abr4xas `node test.js` Doesn't run a test suite; it's a test script to which you need to supply a feed url to test.

``` bash
node test.js http://cyber.law.harvard.edu/rss/examples/rss2sample.xml
```

Or you can test all the configured feeds:

``` bash
node test.js http://cyber.law.harvard.edu/rss/examples/rss2sample.xml
```
